# Generated by Django 3.2 on 2021-05-19 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['attendee'],
            },
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.CharField(blank=True, default='THE DREAM CENTRE CHURCH', max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.CharField(default='THE DREAM CENTRE CHURCH', max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, default='event_default.jpg', upload_to='event_pics')),
                ('description', models.TextField(default='Come all things are Ready. Jesus is Lord!')),
                ('section', models.IntegerField(blank=True, default=5, null=True)),
                ('chat_intro', models.TextField(default='Come all things are Ready. Jesus is Lord!')),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('chat_pass', models.CharField(blank=True, max_length=50)),
                ('attendee', models.ManyToManyField(through='events.Attendance', to='events.Attendee')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('access', models.CharField(blank=True, max_length=20, null=True)),
                ('organization', models.CharField(default='THE DREAM CENTRE CHURCH', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_limit', models.IntegerField(blank=True, default=15, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('reg_attendee', models.ManyToManyField(blank=True, to='events.Attendee')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(default='Come all things are Ready. Jesus is Lord!', null=True)),
                ('upvote', models.CharField(blank=True, default='5', max_length=10, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.attendee')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('voters', models.ManyToManyField(blank=True, related_name='voters', to='events.Attendee')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendee_main', to='events.attendee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in',
            field=models.ManyToManyField(blank=True, to='events.CheckIn'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('attendee', 'event')},
        ),
    ]
