# Generated by Django 3.2 on 2021-05-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='Subscription',
            new_name='EventSubscriber',
        ),
    ]
