# Generated by Django 3.2 on 2021-07-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20210701_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='upvote',
            field=models.CharField(blank=True, default='5a', max_length=10, null=True),
        ),
    ]
