# Generated by Django 3.2 on 2021-05-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch_operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchbranch',
            name='pass_1',
        ),
        migrations.RemoveField(
            model_name='churchbranch',
            name='pass_2',
        ),
    ]
